import localFont from "next/font/local";
import "./globals.css";

const matrixtype = localFont({
  src: "../public/fonts/SekaiwoRegular.ttf",
  variable: "--font-matrix",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${matrixtype.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
